development:
  adapter: mysql
  database: mundo_pepino_dev
  host: localhost
  username: root
  password:

test:
  adapter: mysql
  database: mundo_pepino_test
  host: localhost
  username: root
  password:
